#!/bin/bash
rutorrent_dir=/var/www/rutorrent
echo "Installez pour l'utilisateur:"
read user
egrep "^$user" /etc/passwd >/dev/null || echo "L'utilisateur n'existe pas!"

echo "Entrer un port pour autodl-irssi"
    read -p  "entrer le port: " port
    echo "Entrer le mot de passe de autodl-irssi "
    read -p  "Mot de passe: " pw

# gestionnaire de paquet
if [ "`dpkg --status aptitude | grep Status:`" == "Status: install ok installed" ]
then
        packetg="aptitude"
else
        packetg="apt-get"
fi

$packetg update
$packetg safe-upgrade -y
$packetg install -y irssi libarchive-zip-perl libnet-ssleay-perl libhtml-parser-perl libxml-libxml-perl libdigest-sha-perl  libjson-perl libjson-xs-perl libxml-libxslt-perl

chown -R $user:$user /home/$user
chown root:$user /home/$user
chmod 755 /home/$user

cd /home/$user
mkdir -p .irssi
cd .irssi
## svn autodl-irssi
svn export https://svn.code.sf.net/p/autodl-irssi/code/trunk/src scripts
mkdir scripts/autorun/
cp scripts/autodl-irssi.pl scripts/autorun/
mkdir -p /home/$user/.autodl
touch /home/$user/.autodl/autodl.cfg

cd /var/www/rutorrent/plugins
svn co https://svn.code.sf.net/p/autodl-irssi/code/trunk/rutorrent/autodl-irssi
chown -R www-data:www-data autodl-irssi
if [ -d "$rutorrent_dir/conf/users/$user/plugins" ]
then
	mkdir $rutorrent_dir/conf/users/$user/plugins/autodl-irssi
else
	mkdir $rutorrent_dir/conf/users/$user/plugins
	mkdir $rutorrent_dir/conf/users/$user/plugins/autodl-irssi
fi
##on donne les permission


##fichier configuration user conf.php
cat <<'EOF' > $rutorrent_dir/conf/users/$user/plugins/autodl-irssi/conf.php
<?php

$autodlPort = @port@;
$autodlPassword = "@pw@";

?>
EOF

sed -i.bak "s/@port@/$port/g;" $rutorrent_dir/conf/users/$user/plugins/autodl-irssi/conf.php
sed -i.bak "s/@pw@/$pw/g;" $rutorrent_dir/conf/users/$user/plugins/autodl-irssi/conf.php

## Fichier configuration autodl.cfg
cat <<'EOF' > /home/$user/.autodl/autodl.cfg
options]
gui-server-port = @port@
gui-server-password = @pw@
EOF

sed -i.bak "s/@port@/$port/g;" /home/$user/.autodl/autodl.cfg
sed -i.bak "s/@pw@/$pw/g;" /home/$user/.autodl/autodl.cfg

